name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        # Instala dependências básicas e adiciona suporte a pacotes legados se preciso
        sudo apt-get install -y \
            git zip unzip openjdk-17-jdk autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            cmake libffi-dev libssl-dev ccache
            
        # Solução para o libtinfo5 em sistemas Ubuntu modernos
        sudo apt-get install -y wget
        wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb
        sudo dpkg -i libtinfo5_6.4-2_amd64.deb

        pip install --upgrade pip
        pip install Cython==0.29.36 buildozer

    - name: Build with Buildozer
      run: buildozer --debug android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk     
